name: C/C++ CI

on:
  push:
    paths:
      - 'src/**'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: update
      run: sudo apt update -y
    - name: upgrade
      run: sudo apt upgrade -y
    - name: install
      run: sudo apt install libboost-all-dev libncurses-dev libfftw3-dev libtinfo-dev libreadline-dev libcurl4-openssl-dev libtag1-dev libmpdclient-dev -y
    - name: autogen
      run: ./autogen.sh
      working-directory: .
    - name: configure
      run: ./configure --prefix=/usr --enable-outputs --enable-clock --enable-visualizer --with-fftw --without-taglib
      working-directory: .
    - name: make
      run: make
      working-directory: .